version: "3.8"
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: mamushi
      POSTGRES_PASSWORD: mamushi
      POSTGRES_DB: mamushi
    restart: always
    networks:
      - lesson
networks:
  lesson: